apiVersion: v1
kind: Service
metadata:
  name: orcestra-final-service
  labels:
    app: orcestra-final
spec:
  type: ClusterIP
  selector:
    app: orcestra-final
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None

